IF SCHEMA_ID('Std') IS NULL
    EXEC('CREATE SCHEMA Std');
GO
IF SCHEMA_ID('Inst') IS NULL
    EXEC('CREATE SCHEMA Inst');
GO
IF SCHEMA_ID('Dept') IS NULL
    EXEC('CREATE SCHEMA Dept');
GO
IF SCHEMA_ID('Course') IS NULL
    EXEC('CREATE SCHEMA Course');
GO
IF SCHEMA_ID('School') IS NULL
    EXEC('CREATE SCHEMA School');
GO
IF SCHEMA_ID('Analytics') IS NULL
    EXEC('CREATE SCHEMA Analytics');
GO
