USE WheresMyScheduleDB;
GO

CREATE OR ALTER PROCEDURE Inst.sp_AddInstructor
    @FName        VARCHAR(50),
    @LName        VARCHAR(50),
    @Email        VARCHAR(100),
    @DepartmentID VARCHAR(30)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM Dept.Department WHERE DepartmentID = @DepartmentID)
        RAISERROR('Department does not exist.', 16, 1);

    -- Check for duplicate email (since ID is auto-gen, we check email unique constraint)
    IF EXISTS (SELECT 1 FROM Inst.Instructor WHERE Email = @Email)
        RAISERROR('Instructor with this email already exists.', 16, 1);

    -- ID will be generated by Trigger
    INSERT INTO Inst.Instructor (InstructorID, FName, LName, Email, DepartmentID)
    VALUES (NULL, @FName, @LName, @Email, @DepartmentID);
END
GO
